import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider"
import {NewsProvider} from "@/context/news-context";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html suppressHydrationWarning>
      <body>
        <Provider>
            <NewsProvider>
                {children}
            </NewsProvider>
        </Provider>
      </body>
      </html>
  );
}
